// Code generated by running "go generate" in github.com/go-enjin/golang-org-x-text. DO NOT EDIT.

//go:build !exclude_enjin_locales

package be

import (
	"github.com/go-enjin/golang-org-x-text/language"
	"github.com/go-enjin/golang-org-x-text/message/catalog"
)

var LocalesCatalog catalog.Catalog

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en": &dictionary{index: enIndex, data: enData},
		"ja": &dictionary{index: jaIndex, data: jaData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	LocalesCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"%[1]d-%[2]d minutes":   9,
	"%d results found":      12,
	"1 result found":        11,
	"Bad Gateway":           6,
	"Bad Request":           0,
	"Forbidden":             2,
	"Internal Server Error": 5,
	"Method Not Allowed":    4,
	"No results found":      10,
	"Not Found":             3,
	"Page %d of %d":         13,
	"Service Unavailable":   7,
	"Showing #%d of %d":     14,
	"Showing %d-%d of %d":   15,
	"Unauthorized":          1,
	"search form expired":   8,
}

var enIndex = []uint32{ // 17 elements
	0x00000000, 0x0000000c, 0x00000019, 0x00000023,
	0x0000002d, 0x00000040, 0x00000056, 0x00000062,
	0x00000076, 0x0000008a, 0x000000cc, 0x000000dd,
	0x000000ec, 0x00000100, 0x00000114, 0x0000012c,
	0x00000149,
} // Size: 92 bytes

const enData string = "" + // Size: 329 bytes
	"\x02Bad Request\x02Unauthorized\x02Forbidden\x02Not Found\x02Method Not " +
	"Allowed\x02Internal Server Error\x02Bad Gateway\x02Service Unavailable" +
	"\x02search form expired\x14\x02\x80\x01=\x00\x13\x02less than a minute=" +
	"\x01\x0f\x02about a minute\x00\x14\x02%[1]d-%[2]d minutes\x02No results " +
	"found\x021 result found\x02%[1]d results found\x02Page %[1]d of %[2]d" +
	"\x02Showing #%[1]d of %[2]d\x02Showing %[1]d-%[2]d of %[3]d"

var jaIndex = []uint32{ // 17 elements
	0x00000000, 0x0000000c, 0x00000016, 0x0000002f,
	0x0000003f, 0x0000005b, 0x00000077, 0x00000083,
	0x00000097, 0x000000b9, 0x000000fb, 0x00000120,
	0x0000014d, 0x00000168, 0x00000182, 0x000001a0,
	0x000001c4,
} // Size: 92 bytes

const jaData string = "" + // Size: 452 bytes
	"\x02Bad Request\x02未認証\x02アクセス権がない\x02存在しない\x02そのメソッドは不可\x02サーバ内部のエラー" +
	"\x02Bad Gateway\x02Service Unavailable\x02検索フォームの時間切れ\x14\x02\x80\x01=" +
	"\x00\x13\x02less than a minute=\x01\x0f\x02about a minute\x00\x14\x02%[1" +
	"]d-%[2]d minutes\x02一致する結果はありません\x021 件の検索結果が見つかりました\x02検索該当件数%[1]d件\x02" +
	"%[2]dページ中の%[1]d\x02%[2]d件中の%[1]d を表示\x02%[3]d件中の%[1]d-%[2]d を表示"

	// Total table size 965 bytes (0KiB); checksum: BB4C9B53
